In [2]:
import tushare as ts

In [5]:
#获取上证指数k线数据，其它参数与个股一致，下同
ts.get_hist_data('sh',start='2018-07-01',end='2018-07-30')

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20
date,,,,,,,,,,,,,
2018-07-23,2815.20,2863.57,2859.54,2809.62,1733828.00,30.27,1.07,2809.350,2813.503,2802.242,1320294.73,1276467.96,1282851.17
2018-07-20,2769.75,2837.86,2829.27,2753.84,1459076.88,56.72,2.05,2800.250,2809.060,2802.232,1189063.43,1224634.48,1257118.61
2018-07-19,2791.02,2805.01,2772.55,2764.49,1144864.88,-14.71,-0.53,2800.632,2800.856,2805.257,1132626.75,1215021.16,1247236.33
2018-07-18,2801.78,2818.40,2787.26,2786.04,1209611.62,-10.87,-0.39,2813.654,2796.989,2810.420,1197614.17,1229760.79,1267182.26
2018-07-17,2806.89,2806.92,2798.13,2774.76,1054092.25,-15.91,-0.56,2811.756,2794.176,2816.843,1209334.15,1232061.80,1278852.39
2018-07-16,2827.08,2837.51,2814.04,2804.49,1077671.50,-17.14,-0.60,2817.656,2793.052,2822.328,1232641.20,1269151.04,1341422.81
2018-07-13,2831.43,2835.46,2831.18,2818.85,1176893.50,-6.48,-0.23,2817.870,2789.204,2832.721,1260205.52,1298418.92,1359805.53
2018-07-12,2771.04,2844.19,2837.66,2771.04,1469802.00,59.89,2.16,2801.080,2790.828,2843.370,1297415.57,1306401.26,1358695.59
2018-07-11,2780.70,2794.36,2777.77,2752.44,1268211.50,-49.86,-1.76,2780.324,2785.752,2853.977,1261907.40,1277778.97,1345009.44
2018-07-10,2819.71,2828.49,2827.63,2800.63,1170627.50,12.52,0.45,2776.596,2789.293,2869.078,1254789.45,1280378.66,1338236.41
2018-07-09,2752.45,2815.79,2815.11,2752.45,1215493.12,67.88,2.47,2768.448,2790.981,2880.336,1305660.87,1289234.37,1333986.93
2018-07-06,2731.35,2768.87,2747.23,2691.02,1362943.75,13.35,0.49,2760.538,2795.404,2892.938,1336632.32,1289602.75,1340556.39
2018-07-05,2755.34,2777.52,2733.88,2727.94,1292261.12,-25.25,-0.92,2780.576,2809.657,2911.051,1315386.95,1279451.50,1336301.69
2018-07-04,2776.63,2793.18,2759.13,2754.16,1232621.75,-27.76,-1.00,2791.180,2823.850,2930.116,1293650.55,1304603.73,1331786.70
2018-07-03,2774.57,2786.89,2786.89,2722.45,1424984.62,11.33,0.41,2801.990,2839.510,2947.870,1305967.88,1325642.98,1329523.41
2018-07-02,2841.58,2845.68,2775.56,2756.82,1370350.38,-71.86,-2.52,2813.514,2851.603,2963.085,1272807.88,1413694.59,1315571.13

In [11]:
#获取深圳成指k线数据
ts.get_hist_data('sz',start='2018-07-01',end='2018-07-30')

In [12]:
#获取沪深300指数k线数据
ts.get_hist_data('hs300',start='2018-07-01',end='2018-07-30')

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20
date,,,,,,,,,,,,,
2018-07-20,3426.46,3505.93,3492.89,3398.95,1019847.25,64.55,1.88,3454.804,3458.200,3447.796,734515.70,754758.63,788380.79
2018-07-19,3444.80,3466.51,3428.34,3417.96,684777.19,-2.98,-0.09,3454.764,3445.423,3453.596,676458.05,738871.49,774947.36
2018-07-18,3456.61,3479.26,3431.32,3430.16,665303.31,-18.06,-0.52,3465.308,3436.833,3461.828,732209.74,751981.75,787662.77
2018-07-17,3466.42,3467.19,3449.38,3420.97,619830.75,-22.71,-0.65,3460.550,3430.076,3472.034,743230.97,760609.42,797756.66
2018-07-16,3488.97,3506.24,3472.09,3459.73,682820.00,-20.60,-0.59,3464.178,3426.066,3480.621,758362.47,793905.04,847118.39
2018-07-13,3488.50,3499.76,3492.69,3474.91,729559.00,11.63,0.33,3461.596,3419.653,3494.688,775001.56,809974.49,855721.84
2018-07-12,3403.33,3499.10,3481.06,3403.33,963535.62,73.53,2.16,3436.082,3421.482,3508.722,801284.92,814275.62,853479.55
2018-07-11,3398.93,3427.57,3407.53,3375.14,720409.50,-59.99,-1.73,3408.358,3415.729,3524.086,771753.76,793840.11,838491.75
2018-07-10,3464.91,3474.14,3467.52,3437.27,695488.25,8.34,0.24,3399.602,3420.902,3545.007,777987.86,803290.98,839074.40
2018-07-09,3378.91,3459.32,3459.18,3378.91,766015.44,94.06,2.79,3387.954,3427.261,3560.630,829447.60,818727.42,838654.90
2018-07-06,3347.06,3396.25,3365.12,3295.73,860975.81,22.68,0.68,3377.710,3437.391,3576.652,844947.41,822002.95,842022.80
2018-07-05,3365.55,3398.49,3342.44,3330.71,815879.81,-21.31,-0.63,3406.882,3461.769,3599.946,827266.31,811023.23,839102.09
2018-07-04,3398.78,3418.33,3363.75,3359.09,751580.00,-45.53,-1.33,3423.100,3486.822,3624.692,815926.45,823343.80,834866.71
2018-07-03,3410.48,3422.04,3409.28,3319.29,952786.94,1.32,0.04,3442.202,3513.991,3648.770,828594.09,834903.90,836631.39
2018-07-02,3504.46,3506.90,3407.96,3383.50,843514.50,-103.02,-2.93,3466.568,3535.175,3668.685,808007.24,900331.74,827304.22

In [14]:
#获取上证50指数k线数据
ts.get_hist_data('sz50', start='2018-07-01',end='2018-07-30')

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20
date,,,,,,,,,,,,,
2018-07-20,2426.10,2506.94,2493.77,2409.05,344534.72,67.61,2.79,2443.980,2454.618,2443.393,218491.78,222960.81,234468.80
2018-07-19,2432.89,2452.45,2426.16,2418.66,204460.55,5.40,0.22,2440.598,2445.503,2447.890,189249.03,213429.37,227071.48
2018-07-18,2437.38,2458.48,2420.76,2419.32,178074.66,-9.68,-0.40,2450.290,2440.323,2455.535,203005.11,218251.95,229164.64
2018-07-17,2443.55,2446.10,2430.44,2414.35,166664.33,-18.33,-0.75,2452.594,2435.090,2464.413,209093.98,220108.96,232176.34
2018-07-16,2471.15,2484.17,2448.77,2438.86,198724.62,-28.09,-1.13,2460.752,2430.944,2472.880,218508.03,232517.21,252630.30
2018-07-13,2480.82,2481.56,2476.86,2464.95,198321.00,2.24,0.09,2465.256,2424.705,2483.841,227429.84,238752.90,255503.26
2018-07-12,2425.67,2490.44,2474.62,2425.67,273240.94,42.34,1.74,2450.408,2425.010,2493.563,237609.70,239683.45,256265.69
2018-07-11,2420.18,2443.35,2432.28,2409.31,208519.02,-38.95,-1.58,2430.356,2420.066,2503.413,233498.79,235215.41,252297.23
2018-07-10,2475.98,2477.84,2471.23,2448.86,213734.59,-0.06,-0.00,2417.586,2422.102,2516.184,231123.94,241790.42,251692.78
2018-07-09,2410.52,2471.80,2471.29,2410.52,243333.66,68.67,2.86,2401.136,2425.651,2525.643,246526.39,246867.07,250893.56
2018-07-06,2378.87,2422.40,2402.62,2349.48,249220.30,28.26,1.19,2384.154,2432.168,2534.683,250075.96,245976.78,251742.48
2018-07-05,2370.86,2398.56,2374.36,2352.97,252686.39,5.93,0.25,2399.612,2450.277,2549.314,241757.20,240713.59,251036.98
2018-07-04,2381.25,2403.51,2368.43,2365.89,196644.77,-20.55,-0.86,2409.776,2470.746,2565.205,236932.02,240077.33,248664.22
2018-07-03,2389.36,2395.08,2388.98,2331.84,290746.81,2.60,0.11,2426.618,2493.736,2582.134,252456.91,244243.71,249939.19
2018-07-02,2473.31,2473.73,2386.38,2370.40,261081.52,-93.53,-3.77,2450.166,2514.816,2597.414,247207.74,272743.39,246674.99

In [16]:
#获取中小板指数k线数据
ts.get_hist_data('zxb', start='2018-07-01',end='2018-07-30')

In [18]:
#获取创业板指数k线数据
ts.get_hist_data('cyb', start='2018-07-01',end='2018-07-30')

In [3]:
df = ts.get_hist_data('300036')

In [4]:
df

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20
date,,,,,,,,,,,,,
2018-07-20,21.27,23.36,23.36,20.58,285217.94,2.12,9.98,21.416,21.006,20.479,203027.90,211702.43,208217.12
2018-07-19,20.31,21.53,21.24,20.08,237180.05,0.84,4.12,20.804,20.744,20.248,179878.59,214353.52,200045.24
2018-07-18,21.01,21.11,20.40,20.40,120305.32,-0.75,-3.55,20.672,20.590,20.068,182143.04,210405.44,192780.61
2018-07-17,20.99,21.16,21.15,19.98,175319.77,0.22,1.05,20.566,20.501,19.947,209358.56,216870.16,191965.90
2018-07-16,20.21,21.59,20.93,20.15,197116.41,0.63,3.10,20.574,20.457,19.744,214527.74,219714.13,188143.40
2018-07-13,20.57,21.00,20.30,19.92,169471.41,-0.28,-1.36,20.596,20.361,19.602,220376.96,215256.89,183077.62
2018-07-12,19.80,21.34,20.58,19.67,248502.31,0.71,3.57,20.684,20.370,19.516,248828.44,222424.89,180589.74
2018-07-11,20.43,20.67,19.87,19.42,256382.91,-1.32,-6.23,20.508,20.258,19.405,238667.83,212641.17,171870.55
2018-07-10,20.88,21.67,21.19,20.46,201165.64,0.15,0.71,20.436,20.277,19.334,224381.75,205605.51,162626.66
2018-07-09,20.69,21.12,21.04,20.42,226362.55,0.30,1.45,20.340,20.181,19.190,224900.53,211998.41,158078.63
2018-07-06,19.47,21.67,20.74,19.34,311728.81,1.04,5.28,20.126,19.951,19.084,210136.81,204731.81,150349.86
2018-07-05,19.70,20.85,19.70,19.30,197699.22,0.19,0.97,20.056,19.751,18.983,196021.34,185736.96,137993.03
2018-07-04,20.60,20.61,19.51,19.23,184952.52,-1.20,-5.79,20.008,19.545,18.950,186614.52,175155.78,133121.67
2018-07-03,20.04,20.96,20.71,19.60,203759.55,0.74,3.71,20.118,19.393,18.923,186829.27,167061.65,132099.17
2018-07-02,20.38,20.45,19.97,19.68,152543.95,-0.42,-2.06,20.022,19.031,18.768,199096.28,156572.68,126548.20
2018-06-29,19.60,20.78,20.39,19.50,241151.48,0.93,4.78,19.776,18.842,18.629,199326.80,150898.35,121973.59
2018-06-28,20.00,20.39,19.46,19.41,150665.09,-0.60,-2.99,19.446,18.661,18.479,175452.57,138754.60,115245.93
2018-06-27,19.99,20.50,20.06,19.80,186026.27,-0.17,-0.84,19.082,18.551,18.349,163697.05,131099.93,111434.21
2018-06-26,18.48,20.61,20.23,18.40,265094.62,1.49,7.95,18.668,18.391,18.200,147294.03,119647.80,106616.72
2018-06-25,18.96,19.44,18.74,18.45,153696.55,0.00,0.00,18.040,18.199,18.050,114049.07,104158.85,100360.99
2018-06-22,17.61,19.09,18.74,17.35,121780.30,1.10,6.24,17.908,18.217,18.016,102469.89,95967.92,95366.35
2018-06-21,17.87,18.12,17.64,17.27,91887.51,-0.35,-1.95,17.876,18.214,18.006,102056.62,90249.11,91919.58
2018-06-20,17.08,18.38,17.99,17.06,104011.18,0.90,5.27,18.020,18.355,18.046,98502.81,91087.56,90816.07
2018-06-19,16.46,17.76,17.09,16.46,98869.81,-0.99,-5.48,18.114,18.452,18.088,92001.58,97136.70,88537.12
2018-06-15,18.55,18.69,18.08,17.45,95800.65,-0.50,-2.69,18.358,18.504,18.174,94268.63,96523.72,89368.04
2018-06-14,18.00,19.27,18.58,18.00,119713.97,0.22,1.20,18.526,18.416,18.185,89465.96,93048.83,88796.73
2018-06-13,18.38,18.89,18.36,18.23,74118.44,-0.10,-0.54,18.552,18.296,18.163,78441.60,91737.27,87695.72
2018-06-12,18.55,18.60,18.46,17.81,71505.01,0.15,0.82,18.690,18.146,18.150,83672.31,91768.49,88154.84
2018-06-11,18.95,19.37,18.31,18.10,110205.10,-0.61,-3.22,18.790,18.009,18.155,102271.82,93585.63,89946.77
2018-06-08,18.71,19.09,18.92,18.45,71787.26,0.21,1.12,18.650,17.901,18.141,98778.80,96563.13,91867.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-09-01,24.00,24.38,21.81,21.81,93530.31,-2.42,-9.99,24.126,27.775,30.658,124398.51,120896.38,137343.63
2015-08-31,26.22,26.60,24.23,24.23,110690.85,-2.69,-9.99,24.920,28.824,31.013,123187.43,128681.49,138307.62
2015-08-28,25.38,26.92,26.92,24.53,150264.59,2.45,10.01,25.802,29.919,31.115,110358.53,126733.12,139197.12
2015-08-27,23.94,24.58,24.47,21.18,126911.64,1.27,5.47,26.782,30.762,31.228,107683.76,124317.34,136680.12
2015-08-26,25.00,26.66,23.20,23.20,140595.16,-2.58,-10.01,28.958,31.978,31.580,118228.67,126011.83,137955.15
2015-08-25,25.78,27.00,25.78,25.78,87474.90,-2.86,-9.99,31.424,33.120,32.099,117394.25,124946.63,138770.02
2015-08-24,29.41,30.00,28.64,28.64,46546.35,-3.18,-9.99,32.728,34.034,32.355,134175.55,135903.94,142245.55
2015-08-21,33.56,34.59,31.82,31.82,136890.77,-3.53,-9.99,34.036,34.727,32.640,143107.71,152547.13,148310.02
2015-08-20,35.75,37.49,35.35,34.90,179636.19,-0.18,-0.51,34.742,34.779,32.957,140950.91,158022.20,149156.66
2015-08-19,30.53,35.53,35.53,29.69,136423.05,3.23,10.00,34.998,34.184,33.085,133794.99,151635.63,146321.16
2015-08-18,35.10,37.98,32.30,31.70,171381.38,-2.88,-8.19,34.816,33.541,33.123,132499.00,153790.88,147077.48
2015-08-17,34.80,35.48,35.18,33.90,91207.18,-0.17,-0.48,35.340,33.201,33.166,137632.32,147933.75,145798.33
2015-08-14,37.00,38.00,35.35,35.08,126106.76,-1.28,-3.49,35.418,32.310,33.054,161986.55,151661.11,148831.17
2015-08-13,33.99,36.80,36.63,33.02,143856.56,2.01,5.81,34.816,31.694,32.919,175093.49,149042.90,150167.90
2015-08-12,34.05,36.39,34.62,33.88,129943.14,-0.30,-0.86,33.370,31.181,32.688,169476.27,149898.48,150562.36
2015-08-11,35.98,37.15,34.92,34.65,197047.98,-0.65,-1.83,32.266,31.077,32.559,175082.76,152593.42,151936.98
2015-08-10,34.00,35.57,35.57,33.00,212978.33,3.23,9.99,31.062,30.676,32.390,158235.18,148587.16,148714.76
2015-08-07,29.99,32.34,32.34,29.68,191641.44,2.94,10.00,29.202,30.553,32.145,141335.67,144072.91,143771.41
2015-08-06,27.84,30.37,29.40,27.60,115770.48,0.30,1.03,28.572,31.135,32.129,122992.32,140291.12,139782.24
2015-08-05,30.00,30.50,29.10,27.70,157975.58,0.20,0.69,28.992,31.985,32.377,130320.68,141006.68,141965.13
2015-08-04,26.31,28.90,28.90,26.31,112810.06,2.63,10.01,29.888,32.705,32.705,130104.07,140364.08,140364.08
2015-08-03,28.11,28.47,26.27,26.27,128480.80,-2.92,-10.00,30.290,33.128,33.128,138939.13,143425.64,143425.64
2015-07-31,30.28,31.45,29.19,28.65,99924.67,-2.31,-7.33,31.904,33.985,33.985,146810.15,145293.75,145293.75
2015-07-30,33.00,34.95,31.50,31.25,152412.31,-2.08,-6.19,33.698,34.670,34.670,157589.92,151775.04,151775.04
2015-07-29,31.98,33.85,33.58,28.18,156892.53,2.67,8.64,34.978,35.198,35.198,151692.68,151668.83,151668.83
2015-07-28,31.14,34.98,30.91,30.91,156985.36,-3.43,-9.99,35.522,35.522,35.522,150624.09,150624.09,150624.09
2015-07-27,36.18,40.00,34.34,34.34,167835.89,-3.82,-10.01,36.675,36.675,36.675,149033.78,149033.78,149033.78
2015-07-24,37.93,41.50,38.16,36.60,153823.50,0.26,0.69,37.453,37.453,37.453,142766.41,142766.41,142766.41
2015-07-23,36.68,38.48,37.90,35.08,122926.13,1.60,4.41,37.100,37.100,37.100,137237.86,137237.86,137237.86
2015-07-22,34.59,37.00,36.30,34.00,151549.59,1.20,3.42,36.300,36.300,36.300,151549.59,151549.59,151549.59